default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 
  password: 

development:
  <<: *default
  database: chat_app_dev

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production
  username: chat_app
  password: <%= ENV['SCRABBLE_CLUB_DATABASE_PASSWORD'] %>
